name: "relabeler"
description: "A GitHub Action that is able to label issues and pull requests on events."
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
  repositoryToken:
    required: true
    description: "The GitHub repository token"
  configPath:
    description: "Path to the configuration file relative to the repository root"
    required: false
outputs:
  time:
    description: "The time we greeted you"
  repository:
    description: "The current repository"
branding:
  icon: "tag"
  color: "white"
