# This is the Azure Pipelines configuration for the relabeler project. IT IS NOT ACTIVATED.
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/*
      - package.json

pr:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "npm install"

  - script: |
      npm run build
    displayName: "npm build"

  - script: |
      npm test
    displayName: "npm test and coverage"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/TEST-*.xml"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: "Cobertura" # cSpell: ignore Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"
      artifact: "coverage-report"
      publishLocation: "pipeline"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/dist"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(Build.ArtifactStagingDirectory)"
      artifact: "build-artifact"
      publishLocation: "pipeline"
